### ISSUE TITLE
How do you use this? :)

### ISSUE THREAD

**Issue by pinkfish** [ChFlick/prettier-plugin-firestore-rules#3]
FOund it, but I cannot seem to install and use it.  Put this in the project.json but it doesn't seem to work with prettier

    "prettier-plugin-firestore-rules": "github:ChFlick/prettier-plugin-firestore-rules#master",

**Comment by ChFlick** [comment]
Hi @pinkfish, thanks for your interest in this plugin, but it's still very much WIP and not ready to be really used.

Currently the `let x = ` syntax as well as everything regarding comments is not yet supported.

Nevertheless, if you want to actually use it I think the best way to use it is the CLI via the `--plugin <path/to/folder>` syntax.
I just published a alpha version to npm, as the [Guide](https://prettier.io/docs/en/plugins.html#using-plugins) states that prettier checks for plugins in the node_moduels, though that did not work for me.

**Comment by ChFlick** [comment]
Hi @pinkfish, if you're still interested: I published a beta version that should be ready to use, though it still lacks proper testing.

I also added a usage section to the README

**Comment by pinkfish** [comment]
Sounds good!   Thanks.  Formatting by hand is annoying :).  Will take a look
