### ISSUE TITLE
Support for "existence in list" expressions

### ISSUE THREAD

**Issue by sgioia9** [ChFlick/prettier-plugin-firestore-rules#5]
If I feed the following snippet to prettier:
```
rules_version = '2';
service cloud.firestore {
  function foo() {
    return 1 in [1, 2]
  }
}
```

I get:
```
firestore.rules: SyntaxError: Expected "!=", "&&", "(", ";", "<", "<=", "==", ">", ">=", "is", "||", "}", comment, or whitespace but "i" found.
```

I'm guessing the issue is that the `in` ([Security Rules](https://firebase.google.com/docs/rules/rules-language)) operator isn't considered part of the grammar?

**Comment by ChFlick** [comment]
Oh yeah, that seems to be the issue, thanks for reporting it.

I'll look into it!

**Comment by ChFlick** [comment]
Sorry it took so long, I have just published the fix :)
I'm (most likely) going to migrate to [another AST parser](https://github.com/brianneisler/firetree) shorty, which will hopefully improve the plugin a lot :rocket:

**Comment by sgioia9** [comment]
Awesome 🚀
